<title><?php echo htmlspecialchars(html_entity_decode($this->getTitle())) ?></title>
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>"/>

<link rel="icon" href="<?php echo $this->getSkinUrl('favicon.ico') ?>" type="image/x-icon"/>
<link rel="shortcut icon" href="<?php echo $this->getSkinUrl('favicon.ico') ?>" type="image/x-icon"/>

<script type="text/javascript">
    var BLANK_URL = '<?php echo $this->getJsUrl() ?>blank.html';
    var BLANK_IMG = '<?php echo $this->getJsUrl() ?>spacer.gif';
    var BASE_URL = '<?php echo $this->getUrl('*') ?>';
    var SKIN_URL = '<?php echo $this->getSkinUrl() ?>';
</script>

<?php echo $this->getCssJsHtml() ?>

<?php if($this->getCanLoadExtJs()): ?>
<script type="text/javascript">
    Ext.BLANK_IMAGE_URL = BLANK_IMG;
    Ext.UpdateManager.defaults.loadScripts = false;
    Ext.UpdateManager.defaults.disableCaching = true;
</script>
<?php endif; ?>

<script type="text/javascript">
    Fieldset.addToPrefix(<?php echo Mage::helper('adminhtml')->getCurrentUserId() ?>);
</script>

<?php echo $this->helper('core/js')->getTranslatorScript() ?>

<?php if (true || $this->getWysiwygActive()) { ?>
<script type="text/javascript" src="/js/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">
Event.observe(window, 'load', function() {
    'description,short_description,_generaldescription,text,page_content,block_content'.split(',').each(function(dom_id) {
       if ($(dom_id)) {
           $(dom_id).removeClassName('required-entry');
       }
    });
	tinyMCE.init({
	  mode : "exact",
	  elements : "<?php echo $this->getEditableAreas() ? $this->getEditableAreas() : 'description,short_description,_generaldescription,text,page_content,block_content' ?>",
	  theme : "advanced",
	  strict_loading_mode : true,
	  width: "640",
	  height: "350",
	  content_css: "<?php echo $this->getSkinUrl() ?>tinymce_content.css",
	  theme_advanced_toolbar_location : "top",
	  theme_advanced_toolbar_align : "left",
	  theme_advanced_statusbar_location : "bottom",
	  relative_urls : false
	});
});
</script>
<?php } ?>
